### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by princemaple** [cabol/nebulex_ecto#1]
Hi @cabol ,

Yet another cool project.
Will this be released on Hex anytime soon?

**Comment by cabol** [comment]
Hi @princemaple, yes, the idea is to make a release in parallel with Nebulex `v1.0.0`, that's the plan, and that will be ready soon !!

**Comment by princemaple** [comment]
Great, thanks for the reply!

**Comment by cabol** [comment]
Version `0.1.0` released – Finally !!
